# Generated by Django 4.0.4 on 2022-04-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('revision', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
